SCREEN_WIDTH = 1700
SCREEN_HEIGHT = 800
FPS = 90

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
SKY_BLUE = (135, 206, 235)

INITIAL_NUM_BIRDS = 50

DESIRED_NUM_OBSTACLES = 7
OBSTACLE_SPEED = 4
OBSTACLE_HIGH_BIRD_THRESHOLD = 90

COMET_HEAD_WIDTH = 35
COMET_HEAD_HEIGHT = 35
COMET_HEAD_CORE_COLOR = (40, 0, 0, 255)
COMET_HEAD_GLOW_COLOR = (200, 0, 0, 120)

COMET_TRAIL_MAX_PARTICLES = 25
COMET_TRAIL_SPAWN_INTERVAL = 1
COMET_TRAIL_RENDER_WIDTH = 150
COMET_TRAIL_PARTICLE_COLOR = (230, 40, 0) # Main red/orange particles

COMET_PARTICLE_INITIAL_RADIUS = 12
COMET_PARTICLE_RADIUS_DECAY = 0.25
COMET_PARTICLE_INITIAL_ALPHA = 200
COMET_PARTICLE_ALPHA_DECAY = 10

# --- Additional Yellow Lingering Particle Settings ---
COMET_TRAIL_YELLOW_PARTICLE_COLOR = (255, 255, 100) # Bright yellow
COMET_YELLOW_PARTICLE_INITIAL_RADIUS = 3           # Smaller than main particles
COMET_YELLOW_PARTICLE_RADIUS_DECAY = 0.03          # Slower radius decay for lingering
COMET_YELLOW_PARTICLE_INITIAL_ALPHA = 220          # Slightly more opaque initially
COMET_YELLOW_PARTICLE_ALPHA_DECAY = 1              # Slower alpha decay for lingering
COMET_YELLOW_PARTICLE_SPAWN_CHANCE = 0.1           # 40% chance to spawn a yellow particle instead of red

FOOD_SPAWN_INTERVAL_FRAMES = 1
MAX_FOOD_ON_SCREEN = 120
FOOD_SIZE = 5

UI_FONT_SIZE = 30
UI_PADDING = 10
UI_LINE_HEIGHT = 30
GAME_LOGIC_UPDATE_INTERVAL_FRAMES = 50
GRAPH_DATA_LOG_INTERVAL_FRAMES = 100

DEFAULT_RADIUS = 4
OBSTACLE_REACTION_DISTANCE_HORIZONTAL = 200
OBSTACLE_VERTICAL_EVASION_MAGNITUDE = 1.5
NUM_FLOCK_NEIGHBORS = 5
REPRODUCTION_THRESHOLD = 2
GLOBAL_SPEED_FACTOR= 2.2
